# Generated by Django 4.0.5 on 2023-05-28 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news24', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, choices=[('Tech', 'Tech'), ('Sports', 'Sports'), ('Fashion', 'Fashion')], max_length=100, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('time', models.DateTimeField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
