# Generated by Django 4.0.5 on 2023-05-28 09:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news24', '0003_alter_news_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, default=django.utils.timezone.now, null=True, upload_to='images/'),
        ),
    ]
