# Generated by Django 4.0.5 on 2023-05-28 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news24', '0006_alter_news_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.CharField(blank=True, choices=[('Tech', 'Tech'), ('Sports', 'Sports'), ('Fashion', 'Fashion'), ('Business', 'Business'), ('Entertainment', 'Entertainment'), ('Latest_News', 'Latest_News')], max_length=100, null=True),
        ),
    ]
